### ISSUE TITLE
Error loading index file in Laravel project.

### ISSUE THREAD

**Issue by rkhitin** [m2mdas/phpcomplete-extended#18] opened 2014-01-02 08:18 UTC
Hi, maybe you can help me. When I try to create an index of the project, I get an error:

```
Generating autoload classmap
Generating index...
Loading Index
Обнаружена ошибка при обработке function phpcomplete_extended#readDataForProject
..phpcomplete_extended#loadProject..<SNR>32_loadIndex..<SNR>32_readIndex:
строка    2:
Could not read index file .phpcomplete_extended/phpcomplete_index
Index Loaded.  
```

**Comment by m2mdas** [comment] 2014-01-02 16:59
It seems that the index file was not created due to error. Can you run `:PHPCompleteExtendedGenerateIndex` and paste the output?

**Comment by m2mdas** [comment] 2014-01-02 17:02
Also can you describe your environment e.g OS, PHP version etc?

**Comment by rkhitin** [comment] 2014-01-03 08:19
Oh, now I think this is my local problem. I forgot to write, first was an error, when generating index -

```
Generating autoload classmap
Generating index... 
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in
/home/ron/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.php on line 1377
PHP Stack trace:
PHP   1. {main}() /home/ron/.vim/bundle/phpcomplete-extended/bin/IndexGenerator.
php:0    
...
```

I fixed it by increasing "xdebug.max_nesting_level" in php.ini.
And now, before the error loading index sometimes there is a system error - crash /usr/bin/php5.

My os - Ubuntu 13.04, PHP - 5.5.7-1+sury.org~raring+1 (cli) (built: Dec 12 2013 22:01:08). 
Installed 'phpcomplete-extended' and 'phpcomplete-extended-laravel' plugins.

And no error before ':PHPCompleteExtendedGenerateIndex', only

```
Generating autoload classmap
Generating index... 
```

But plugin doesn't work.

**Comment by m2mdas** [comment] 2014-01-03 11:00
Hmm, it seems that your project is very large or have many libraries. In that case I would recommend you to disable xdebug in commandline. Index generation time decreases by huge margin if you disable xdebug in commandline. I have added info how to disable xdebug in `readme.md`. Pasting here for convenience. I will put up a FAQ section soon.

`Indexing may take some time depending on project size. To decrease index creation time I would recommend disabling xdebug extension in cli. To do that go to the location where php.ini resides and copy the php.ini file as php-cli.ini and comment out the xdebug line. To verify issue php -m | grep xdebug in commandline.`

Now about PHP version, I am currently testing the plugin in my main Ubuntu 12.04 OS with PHP 5.4 installed and PHP 5.3+5.4 in Windows. Haven't tested in PHP 5.5 due to my laziness to upgrade :). I will fireup a Ubuntu 13.04 VM with PHP 5.5 installed tonight and test the plugin with large project.

**Comment by m2mdas** [comment] 2014-01-03 18:05
On second thought the bug may not be related to PHP version. Because no matter how large the project is there is very little chance that function nesting level will be 100 level deep. I am guessing that the bug may be reated to indexer script. 

I have added `-verbose` option to the `:PHPCompleteExtendedGenerateIndex` command. If `-verbose` option added the plugin will list the fie processed. The output will be huge as there are many files. You can install [tyru/capture.vim](https://github.com/tyru/capture.vim) and use its `:Capture` command to put the output in a scratch buffer. The command would be

```
:Capture PHPCompleteExtendedGenerateIndex -verbose
```

After running the command please post the class structure of the last fie processed including the the class/interface it extends/implements. From FQCN declarations to Class declaration would be enough.

**Comment by rkhitin** [comment] 2014-01-03 18:55
You were right in first comment, it all depends on the size of the project. On a small - everything is fine. At large one - still doesn't work. But anyway - thanks a lot! =)

**Comment by m2mdas** [comment] 2014-01-03 19:30
Well I am not satisfied about it. I am using this plugin with a Symfony2 project consisting of 4000+ files and it is working fine here. The only difference between your environment and mine is OS and PHP version. I am reopening the issue for further investigation. Will give feedback after I have tested with PHP 5.5.

**Comment by m2mdas** [comment] 2014-01-04 10:51
I have tested in Ubuntu 13.04+PHP 5.5. I have found no problem in generating index for large project. Previously I did not handle UTF-8 doc comment. I fixed that now. You can update the plugin to test. 

I am pretty certain that your problem is not related to size of the project. It is related to a unhandeled class naming convention by indexer script. That's why I need class structure of last file processed before crash. I have added `-verbose` option to `:PHPCompleteExtendedGenerateIndex` for this reason. Please run the command and paste the use section to class declaration portion of the last class and the class/interfaces it extends/implements.

**Comment by m2mdas** [comment] 2014-01-04 14:17
I think I have found the bug. It was caused by parsing a class in Sentry package. Please update the plugin and run `:PHPCompleteExtendedGenerateIndex` and `:PHPCompleteExtendedReload`.

**Comment by rkhitin** [comment] 2014-01-04 15:44
You are absolutely right. There is no the previous erorr. Thank you! =)

I have a new one. But it's only for one project, so that there is a problem in project. 

```
Generating autoload classmap
Generating index...
{"error":{"type":"ReflectionException","message":"Class itemconfig does not exis
t","file":"\/var\/www\/newsite\/vendor\/laravel\/framework\/src\/Illuminate\/Con
tainer\/Container.php","line":476}}  

```

Sorry for my English, by the way =)

**Comment by m2mdas** [comment] 2014-01-04 16:03
Great to know that the plugin is working now.  Quick googling the error led to [this issue of `Laravel-Administrator`](https://github.com/FrozenNode/Laravel-Administrator/issues/219). Updating the package will resolve the issue I think. Closing the issue now. If there are any new problem don't hesitate to file new issue report. Will try to fix as soon as I can.

Happy coding :)

**Closed as completed by m2mdas** 2014-01-04 16:03 UTC
Labels: bug
